version: '3'

services:
  msvc-mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_usuario
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cmr
    restart: always

  msvc-usuarios:
    build:
      context: ./msvc-usuario
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://msvc-mysql:3306/db_usuario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msvc-eureka:8761/eureka
    networks:
      - cmr
    restart: always

  msvc-eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - cmr
    restart: always

networks:
  cmr:
    driver: bridge
