# Usa una imagen base de Java
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo JAR de tu aplicación al contenedor
COPY gateway/target/gateway-0.0.1-SNAPSHOT.jar gateway.jar

# Expone el puerto 8761, que es el puerto predeterminado de Eureka
EXPOSE 8090

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["java", "-jar", "gateway.jar"]