# Usa una imagen base de Java
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo JAR de tu aplicación al contenedor
COPY msvc-proceso/target/msvc-proceso-0.0.1-SNAPSHOT.jar msvc-proceso.jar

# Expone el puerto 8761, que es el puerto predeterminado de Eureka
EXPOSE 8080

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["java", "-jar", "msvc-proceso.jar"]