# Usa una imagen base de Java
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo JAR de tu aplicación al contenedor
COPY msvc-cliente/target/msvc-cliente-0.0.1-SNAPSHOT.jar msvc-cliente.jar

# Expone el puerto 8082
EXPOSE 8082

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["java", "-jar", "msvc-cliente.jar"]